### ISSUE TITLE
`in_transform` shouldn't have batchnorm

### ISSUE THREAD

**Issue by abhshkdz** [iassael/torch-bnlstm#1]
`local in_transform = nn.Tanh()(c_bn(sum_splits[4]))` looks slightly off. That would imply equation 7 from [the paper](http://arxiv.org/pdf/1603.09025v3.pdf) to have a `BN` term.

Instead, `local next_h = nn.CMulTable()({ out_gate, nn.Tanh()(next_c) })` should be `local next_h = nn.CMulTable()({ out_gate, nn.Tanh()(c_bn(next_c)) })` (equation 8), or am I missing something?

**Comment by iassael** [comment]
You are right! Thank you.
