### ISSUE TITLE
Just one quick question on LinearNB

### ISSUE THREAD

**Issue by hohoCode** [iassael/torch-bnlstm#2]
Thanks for your BNLSTM opensource. Great work. 

Just one quick question on the codes at Line 39 and Line 41 of LSTM.lua file, where you have:
`nn.LinearNB(input_size, 4 * rnn_size)(x)`
`nn.Linear(rnn_size, 4 * rnn_size)(prev_h)`

So is the difference between your nn.LinearNB and nn.Linear only on weight initializations? If that is the case, just wondering are there any reasons to use different types of linear layers in these two lines? 

Thanks!

**Comment by iassael** [comment]
You only need one bias term not two, where Linear would result:

```
W_h h_{t-1} + W_x x_t + b_h + b_x).
```

In nn.LinearNB, NB stands for no-bias, and it is used as your equation is: 

```
W_h h_{t-1} + W_x x_t + b.
```

 Thank you!

**Comment by hohoCode** [comment]
I see. Thanks!
